### ISSUE TITLE
lancer

### ISSUE THREAD

**Issue by alexpapou** [Quasimewdo/Sherlock13#1]
Bonjour et merci pour ton projet, je n'arrive pas lancer l'app, tu peux me redonner les consignes de lancement svp ? merci encore

**Comment by ruxuez** [comment]
Normalement, après avoir lancer `cmd.sh`, tu obtiens deux exécutables (`server` pour le serveur  et `sh13` pour joueur). Pour pouvoir lancer le jeux, il faut avoir une terminal pour lander le serveur et 4 autres shells pour les 4 joueurs.

server: `./server port_number` par exemple: `./server 32000`
joueur: `./sh13 ip_add port_number player_name ` par exemple: `./sh13 localhost 32001 alice`

**Comment by alexpapou** [comment]
Merci pour ton aide
